### ISSUE TITLE
Cancel Friend Request

### ISSUE THREAD

**Issue by greggh** [artisanry/friendable#21]
I don't see a way to cancel a friend request. Example:

1. User A asks User B to be friends.
2. User B ignores this request.
3. Some time in the future User A looks at the list of open friendship requests and decides to cancel the request to User B.

Is this currently possible?

**Comment by xSINIQx** [comment]
Way too late probably but simply deleting the entry from the friendships table would do the trick.

**Comment by faustbrian** [comment]
Currently there are no plans for this feature but feel free to submit a PR.
