### ISSUE TITLE
  Class 'Artisanry\Debugbar\DebugbarServiceProvider' not found

### ISSUE THREAD

**Issue by SandHoofd** [artisanry/friendable#25]
When I am trying to install the package, I get a error message:
> @php artisan package:discover --ansi

In ProviderRepository.php line 208:

  Class 'Artisanry\Debugbar\DebugbarServiceProvider' not found

Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1

- Version used:
I am using laravel 5.8, php 7.2.19 on Windows 10

**Comment by faustbrian** [comment]
https://github.com/artisanry/friendable/commit/f41f564ac2240bf7602a4aaa6617c4a3818b0854
https://github.com/artisanry/friendable/releases/tag/3.1.1
